title: "天海 Works"
summary: |-
  面接の前に、これまでの仕事をざっと把握していただくための一冊です。
  気になった部分を中心にお話しできればと思います。
topics:
  - "ai"
  - "frontend"
  - "devops"
  - "backend"
  - "agile"
published: false
allow_override: true
price: 5000
toc_depth: 2
chapters:
  - "8e9b12"
  - "f28dbf"
  - "a46f1c"
  - "d78811"
  - "0ba979"
  - "f07bbb"
